logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/cloud_appmanage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password:  123456
  rabbitmq:
    host: local.rabbitmq.com
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  redis:
    host: local.redis.com
    port: 6379
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
mybatis:
  type-aliases-package: com.cloud.model.appmanage
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://api.gateway.com/api/api-o/user-me
      prefer-token-info: false
wechat:
  domain: http://api.gateway.com/api/api-u
  infos:
    app1:
      appid: xxx
      secret: xxx
    app2:
      appid: xxx
      secret: xxx
gitlab:
  apiPrefix: http://10.130.86.36:8889
  private-token: xZJpcZraQFtWRzUZfVdg
  domain: gitlab.hlxd.com
  ip: 10.130.86.36
jenkins:
  jenUrl: http://10.130.86.36:8888/
  username: admin
  passwordorToken: admin
#上传文件地址
web:
 # upload-path: /tools/jar_image/
  upload-path: /Users/fishfly/localFile

#服务器ip 处理静态文件上传
serverIP: localhost

